sonar.projectKey=u03-hospital-despues
sonar.projectName=Hospital Central despues del refactor
sonar.projectVersion=tp3
sonar.sources=hospital
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.python.version=3.14
sonar.python.coverage.reportPaths=docs/tp3/coverage.xml
sonar.host.url=http://localhost:9000
